server:
  port: 8088

logging:
  level:
    org.springframework: info

spring:
  messages:
    basename: messages
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
#  security:
#    user:
#      name: username
#      password: 1234

management:
  endpoints:
    web:
      exposure:
        include: "*"
